In [29]:
from __future__ import division
import pandas as pd
import numpy as np

import seaborn as sns
from matplotlib import pyplot as plt

In [30]:
ratings_train = pd.read_csv('./homework4/data/ratings_train.csv', header=None)
ratings_test = pd.read_csv('./homework4/data/ratings_test.csv', header=None)
ratings_fake = pd.read_csv('./homework4/data/ratings_fake.csv', header=None)

In [31]:
ratings_train.columns = ['user', 'movie', 'rating']
ratings_test.columns = ['user', 'movie', 'rating']
ratings_fake.columns = ['user', 'movie', 'rating']

In [32]:
A = ratings_fake.pivot(index='user', columns='movie').as_matrix()

In [33]:
mu = A.mean()
m = A.shape[0]
n = A.shape[1]
k = 5
T = 20
B = np.zeros(m)
C = np.zeros(n)
U = np.random.multivariate_normal(np.zeros(k), (1/k) * np.identity(k), (m))
V = np.random.multivariate_normal(np.zeros(k), (1/k) * np.identity(k), (n))

In [34]:
B = (-(U * V).sum(axis=1) - C - mu + A.sum(axis=1)) / n

In [35]:
C = (-(U * V).sum(axis=1) - B - mu - A.sum(axis=1) / m)

In [36]:
arrs = []
for i in range(U.shape[0]):
    for j in range(V.shape[0]):
        r = (B[i] + C[j] + mu - A[i, j]) * V[j]
        arrs.append(r)

In [57]:
prods = []
for j in range(V.shape[0]):
    arr = (V[j] * V[j].T)
    prods.append(arr)

In [58]:
p = np.array(prods)

In [63]:
final_arrs = []
for ix in range(200):
    final_arrs.append(p[ix] * arrs[ix])

In [67]:
np.array(final_arrs).sum(axis=0)

array([-14.90964844,  -0.39561065,   0.49120555,  -4.8036366 ,  -6.83091339])

In [ ]:
# for j in range(V.shape[0]):
#     np.linalg.inv(V[j]

In [42]:
np.array(arrs).sum(axis=0)

array([-4792.88097176,  -696.36544412,  2484.15052509, -1136.62497834,
       -4159.18938098])

In [21]:
B[0] + C[0] + mu - A[0, 0] * V[0]

array([-4.77606269, -0.53926344, -2.39429882, -1.96507618, -2.967132  ])

In [207]:
def non_u_component(U, B, C, mu, A):
    new_vec = []
    for i in range(U.shape[0]):
        s = (B[i] + C + mu - A[i, :])
        new_vec.append(s)
        nuc = np.array(new_vec)
    return nuc * V

In [166]:
# def non_v_component(U, B, C, mu, A):
#     new_vec = []
#     for i in range(V.shape[0]):
#         s = (B[i] + C + mu - A[i, :]) * V
#         new_vec.append(s)
#         nc = np.array(new_vec)
#     return nc

In [216]:
(B[0] + C + mu - A[0, :]) * V

ValueError: operands could not be broadcast together with shapes (200,) (200,5) 

In [11]:
# nuc = non_u_component(U, B, C, mu, A)

array([[ 0.02386488,  0.00176408,  0.00128899, -0.00090823, -0.00060981],
       [ 0.00176408,  0.02413522,  0.00141753,  0.00137562,  0.00068568],
       [ 0.00128899,  0.00141753,  0.02990252,  0.00195693, -0.00104276],
       [-0.00090823,  0.00137562,  0.00195693,  0.02420075,  0.00177058],
       [-0.00060981,  0.00068568, -0.00104276,  0.00177058,  0.02142876]])

In [65]:
# global_bs = []
# for user in U:
#     bs = 0
#     for movie in V:
#         b = optimal_b_val(user, movie)
#         bs += b
#     global_bs.append(bs/n)

In [27]:
ratings_train.head()

user  movie  rating
0   721   1026       3
1   407    289       3
2   508    172       5
3   433    474       3
4   207    158       3